# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/wiko/s9091/setup-makefiles.sh

PRODUCT_COPY_FILES := \
    vendor/wiko/s9091/proprietary/lib/libloc.so:obj/lib/libloc.so

PRODUCT_COPY_FILES += \
    vendor/wiko/s9091/proprietary/app/MobileLog.apk:system/app/MobileLog.apk \
    vendor/wiko/s9091/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/wiko/s9091/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/wiko/s9091/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/wiko/s9091/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/wiko/s9091/proprietary/data/misc/acdapi/param.dat:system/data/misc/acdapi/param.dat \
    vendor/wiko/s9091/proprietary/data/misc/acdapi/calib.dat:system/data/misc/acdapi/calib.dat \
    vendor/wiko/s9091/proprietary/data/misc/acdapi/sensors.dat:system/data/misc/acdapi/sensors.dat \
    vendor/wiko/s9091/proprietary/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
    vendor/wiko/s9091/proprietary/lib/libmtkbtextspp.so:system/lib/libmtkbtextspp.so \
    vendor/wiko/s9091/proprietary/lib/libextbpp_jni.so:system/lib/libextbpp_jni.so \
    vendor/wiko/s9091/proprietary/lib/libmediatek_exceptionlog.so:system/lib/libmediatek_exceptionlog.so \
    vendor/wiko/s9091/proprietary/lib/libextsimap_jni.so:system/lib/libextsimap_jni.so \
    vendor/wiko/s9091/proprietary/lib/libamrenc.so:system/lib/libamrenc.so \
    vendor/wiko/s9091/proprietary/lib/libmhal.so:system/lib/libmhal.so \
    vendor/wiko/s9091/proprietary/lib/libextmap_jni.so:system/lib/libextmap_jni.so \
    vendor/wiko/s9091/proprietary/lib/libmp4dec_sb.ca9.so:system/lib/libmp4dec_sb.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libmtka2dp.so:system/lib/libmtka2dp.so \
    vendor/wiko/s9091/proprietary/lib/libextopp_jni.so:system/lib/libextopp_jni.so \
    vendor/wiko/s9091/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxAMRWBDec.so:system/lib/libMtkOmxAMRWBDec.so \
    vendor/wiko/s9091/proprietary/lib/mtk-ril3.so:system/lib/mtk-ril3.so \
    vendor/wiko/s9091/proprietary/lib/libstagefright_pmemutil.so:system/lib/libstagefright_pmemutil.so \
    vendor/wiko/s9091/proprietary/lib/libmhalcontent.so:system/lib/libmhalcontent.so \
    vendor/wiko/s9091/proprietary/lib/libjpeg.so:system/lib/libjpeg.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/wiko/s9091/proprietary/lib/libpalsecurity.so:system/lib/libpalsecurity.so \
    vendor/wiko/s9091/proprietary/lib/libutilitysw.so:system/lib/libutilitysw.so \
    vendor/wiko/s9091/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/wiko/s9091/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
    vendor/wiko/s9091/proprietary/lib/libexthid.so:system/lib/libexthid.so \
    vendor/wiko/s9091/proprietary/lib/libmhalmdp.so:system/lib/libmhalmdp.so \
    vendor/wiko/s9091/proprietary/lib/libh264enc_sa.ca9.so:system/lib/libh264enc_sa.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libextdun_jni.so:system/lib/libextdun_jni.so \
    vendor/wiko/s9091/proprietary/lib/libacdk.so:system/lib/libacdk.so \
    vendor/wiko/s9091/proprietary/lib/libextsimap.so:system/lib/libextsimap.so \
    vendor/wiko/s9091/proprietary/lib/libextpbap_jni.so:system/lib/libextpbap_jni.so \
    vendor/wiko/s9091/proprietary/lib/libmhalutility.so:system/lib/libmhalutility.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/wiko/s9091/proprietary/lib/libc_malloc_debug_mtk.so:system/lib/libc_malloc_debug_mtk.so \
    vendor/wiko/s9091/proprietary/lib/libgiajni.so:system/lib/libgiajni.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/wiko/s9091/proprietary/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
    vendor/wiko/s9091/proprietary/lib/libextjsr82.so:system/lib/libextjsr82.so \
    vendor/wiko/s9091/proprietary/lib/libextsys_jni.so:system/lib/libextsys_jni.so \
    vendor/wiko/s9091/proprietary/lib/libextavrcp.so:system/lib/libextavrcp.so \
    vendor/wiko/s9091/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/wiko/s9091/proprietary/lib/libatvctrlservice.so:system/lib/libatvctrlservice.so \
    vendor/wiko/s9091/proprietary/lib/libmexif.so:system/lib/libmexif.so \
    vendor/wiko/s9091/proprietary/lib/libmobilelog_jni.so:system/lib/libmobilelog_jni.so \
    vendor/wiko/s9091/proprietary/lib/libmhalscenario.so:system/lib/libmhalscenario.so \
    vendor/wiko/s9091/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/wiko/s9091/proprietary/lib/liblog.so:system/lib/liblog.so \
    vendor/wiko/s9091/proprietary/lib/libbtpcm.so:system/lib/libbtpcm.so \
    vendor/wiko/s9091/proprietary/lib/libnativecheck-jni.so:system/lib/libnativecheck-jni.so \
    vendor/wiko/s9091/proprietary/lib/libmp3dec_mtk.so:system/lib/libmp3dec_mtk.so \
    vendor/wiko/s9091/proprietary/lib/libssladp.so:system/lib/libssladp.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    vendor/wiko/s9091/proprietary/lib/libja3m.so:system/lib/libja3m.so \
    vendor/wiko/s9091/proprietary/lib/libMtkVideoTranscoder.so:system/lib/libMtkVideoTranscoder.so \
    vendor/wiko/s9091/proprietary/lib/libh264dec_customize.so:system/lib/libh264dec_customize.so \
    vendor/wiko/s9091/proprietary/lib/libutilril3mtk.so:system/lib/libutilril3mtk.so \
    vendor/wiko/s9091/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/wiko/s9091/proprietary/lib/libh264enc_sb.ca9.so:system/lib/libh264enc_sb.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libpalwlan_mtk.so:system/lib/libpalwlan_mtk.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxAwbEnc.so:system/lib/libMtkOmxAwbEnc.so \
    vendor/wiko/s9091/proprietary/lib/libmtkbtextadp.so:system/lib/libmtkbtextadp.so \
    vendor/wiko/s9091/proprietary/lib/libextpan_jni.so:system/lib/libextpan_jni.so \
    vendor/wiko/s9091/proprietary/lib/libextbip.so:system/lib/libextbip.so \
    vendor/wiko/s9091/proprietary/lib/libexttestmode.so:system/lib/libexttestmode.so \
    vendor/wiko/s9091/proprietary/lib/libextpbap.so:system/lib/libextpbap.so \
    vendor/wiko/s9091/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/wiko/s9091/proprietary/lib/libmp4enc_xb.ca9.so:system/lib/libmp4enc_xb.ca9.so \
    vendor/wiko/s9091/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
    vendor/wiko/s9091/proprietary/lib/libagpssupl.so:system/lib/libagpssupl.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxAmrEnc.so:system/lib/libMtkOmxAmrEnc.so \
    vendor/wiko/s9091/proprietary/lib/libexthid_jni.so:system/lib/libexthid_jni.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxVorbisDec.so:system/lib/libMtkOmxVorbisDec.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxCookDec.so:system/lib/libMtkOmxCookDec.so \
    vendor/wiko/s9091/proprietary/lib/libcameraprofile.so:system/lib/libcameraprofile.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxAacDec.so:system/lib/libMtkOmxAacDec.so \
    vendor/wiko/s9091/proprietary/lib/libextsys.so:system/lib/libextsys.so \
    vendor/wiko/s9091/proprietary/lib/libgia.so:system/lib/libgia.so \
    vendor/wiko/s9091/proprietary/lib/libutilrilmtk.so:system/lib/libutilrilmtk.so \
    vendor/wiko/s9091/proprietary/lib/libmpo.so:system/lib/libmpo.so \
    vendor/wiko/s9091/proprietary/lib/libmtkbtextpan.so:system/lib/libmtkbtextpan.so \
    vendor/wiko/s9091/proprietary/lib/libextftp_jni.so:system/lib/libextftp_jni.so \
    vendor/wiko/s9091/proprietary/lib/libmemorydumper.so:system/lib/libmemorydumper.so \
    vendor/wiko/s9091/proprietary/lib/libdvm.so:system/lib/libdvm.so \
    vendor/wiko/s9091/proprietary/lib/libmhalpipe.so:system/lib/libmhalpipe.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxAacEnc.so:system/lib/libMtkOmxAacEnc.so \
    vendor/wiko/s9091/proprietary/lib/libextftp.so:system/lib/libextftp.so \
    vendor/wiko/s9091/proprietary/lib/librv9dec_xa.ca9.so:system/lib/librv9dec_xa.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libacdapi_azi.so:system/lib/libacdapi_azi.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxAMRNBDec.so:system/lib/libMtkOmxAMRNBDec.so \
    vendor/wiko/s9091/proprietary/lib/libmdlogger_ctrl_jni.so:system/lib/libmdlogger_ctrl_jni.so \
    vendor/wiko/s9091/proprietary/lib/libmp4dec_sa.ca9.so:system/lib/libmp4dec_sa.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    vendor/wiko/s9091/proprietary/lib/libextbip_jni.so:system/lib/libextbip_jni.so \
    vendor/wiko/s9091/proprietary/lib/libmpodecoder.so:system/lib/libmpodecoder.so \
    vendor/wiko/s9091/proprietary/lib/libril3mtk.so:system/lib/libril3mtk.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    vendor/wiko/s9091/proprietary/lib/libmtkbtextadpa2dp.so:system/lib/libmtkbtextadpa2dp.so \
    vendor/wiko/s9091/proprietary/lib/librv9dec_customize.so:system/lib/librv9dec_customize.so \
    vendor/wiko/s9091/proprietary/lib/libmp4enc_xa.ca9.so:system/lib/libmp4enc_xa.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libipto3d.so:system/lib/libipto3d.so \
    vendor/wiko/s9091/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/wiko/s9091/proprietary/lib/libh264dec_xb.ca9.so:system/lib/libh264dec_xb.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/wiko/s9091/proprietary/lib/libextmap.so:system/lib/libextmap.so \
    vendor/wiko/s9091/proprietary/lib/libmp4dec_customize.so:system/lib/libmp4dec_customize.so \
    vendor/wiko/s9091/proprietary/lib/libJniAtvService.so:system/lib/libJniAtvService.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    vendor/wiko/s9091/proprietary/lib/libmhaldrv.so:system/lib/libmhaldrv.so \
    vendor/wiko/s9091/proprietary/lib/libh264dec_xa.ca9.so:system/lib/libh264dec_xa.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    vendor/wiko/s9091/proprietary/lib/libpppbtdun.so:system/lib/libpppbtdun.so \
    vendor/wiko/s9091/proprietary/lib/libvp8dec_xa.ca9.so:system/lib/libvp8dec_xa.ca9.so \
    vendor/wiko/s9091/proprietary/lib/libextbpp.so:system/lib/libextbpp.so \
    vendor/wiko/s9091/proprietary/lib/libextopp.so:system/lib/libextopp.so \
    vendor/wiko/s9091/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/wiko/s9091/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
    vendor/wiko/s9091/proprietary/lib/libmdlogger_ctrl.so:system/lib/libmdlogger_ctrl.so \
    vendor/wiko/s9091/proprietary/lib/liba3m.so:system/lib/liba3m.so \
    vendor/wiko/s9091/proprietary/lib/libeis.so:system/lib/libeis.so \
    vendor/wiko/s9091/proprietary/lib/libipto3djni.so:system/lib/libipto3djni.so \
    vendor/wiko/s9091/proprietary/lib/libextavrcp_jni.so:system/lib/libextavrcp_jni.so \
    vendor/wiko/s9091/proprietary/lib/drm/libdrmmtkplugin.so:system/lib/drm/libdrmmtkplugin.so \
    vendor/wiko/s9091/proprietary/lib/modules/wlan_mt6628.ko:system/lib/modules/wlan_mt6628.ko \
    vendor/wiko/s9091/proprietary/lib/modules/devapc.ko:system/lib/modules/devapc.ko \
    vendor/wiko/s9091/proprietary/lib/modules/m4u.ko:system/lib/modules/m4u.ko \
    vendor/wiko/s9091/proprietary/lib/modules/wlan_mt6620.ko:system/lib/modules/wlan_mt6620.ko \
    vendor/wiko/s9091/proprietary/lib/modules/ccmni.ko:system/lib/modules/ccmni.ko \
    vendor/wiko/s9091/proprietary/lib/modules/devinfo.ko:system/lib/modules/devinfo.ko \
    vendor/wiko/s9091/proprietary/lib/modules/p2p_mt6628.ko:system/lib/modules/p2p_mt6628.ko \
    vendor/wiko/s9091/proprietary/lib/modules/p2p_mt6620.ko:system/lib/modules/p2p_mt6620.ko \
    vendor/wiko/s9091/proprietary/lib/modules/alps_core.ko:system/lib/modules/alps_core.ko \
    vendor/wiko/s9091/proprietary/lib/modules/ccci.ko:system/lib/modules/ccci.ko \
    vendor/wiko/s9091/proprietary/lib/modules/vcodec_kernel_driver.ko:system/lib/modules/vcodec_kernel_driver.ko \
    vendor/wiko/s9091/proprietary/lib/modules/aed.ko:system/lib/modules/aed.ko \
    vendor/wiko/s9091/proprietary/lib/hw/mmumapper.mt6577.so:system/lib/hw/mmumapper.mt6577.so \
    vendor/wiko/s9091/proprietary/lib/hw/hwcomposer.mt6577.so:system/lib/hw/hwcomposer.mt6577.so \
    vendor/wiko/s9091/proprietary/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/wiko/s9091/proprietary/bin/thermal_manager:system/bin/thermal_manager \
    vendor/wiko/s9091/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/wiko/s9091/proprietary/bin/magd:system/bin/magd \
    vendor/wiko/s9091/proprietary/bin/btlogmask:system/bin/btlogmask \
    vendor/wiko/s9091/proprietary/bin/msensord:system/bin/msensord \
    vendor/wiko/s9091/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/wiko/s9091/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
    vendor/wiko/s9091/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/wiko/s9091/proprietary/bin/muxreport:system/bin/muxreport \
    vendor/wiko/s9091/proprietary/bin/memsicd:system/bin/memsicd \
    vendor/wiko/s9091/proprietary/bin/mdlogger:system/bin/mdlogger \
    vendor/wiko/s9091/proprietary/bin/stp_dump3:system/bin/stp_dump3 \
    vendor/wiko/s9091/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/wiko/s9091/proprietary/bin/mdpd:system/bin/mdpd \
    vendor/wiko/s9091/proprietary/bin/md_minilog_util:system/bin/md_minilog_util \
    vendor/wiko/s9091/proprietary/bin/mtkbt:system/bin/mtkbt \
    vendor/wiko/s9091/proprietary/bin/rild:system/bin/rild \
    vendor/wiko/s9091/proprietary/bin/xlog:system/bin/xlog \
    vendor/wiko/s9091/proprietary/bin/mdpserver:system/bin/mdpserver \
    vendor/wiko/s9091/proprietary/bin/btconfig:system/bin/btconfig \
    vendor/wiko/s9091/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
    vendor/wiko/s9091/proprietary/bin/ami304d:system/bin/ami304d \
    vendor/wiko/s9091/proprietary/bin/netdiag:system/bin/netdiag \
    vendor/wiko/s9091/proprietary/bin/fsck_msdos_mtk:system/bin/fsck_msdos_mtk \
    vendor/wiko/s9091/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/wiko/s9091/proprietary/bin/mfv_ut:system/bin/mfv_ut \
    vendor/wiko/s9091/proprietary/bin/AcdApiDaemon:system/bin/AcdApiDaemon \
    vendor/wiko/s9091/proprietary/bin/rild3:system/bin/rild3 \
    vendor/wiko/s9091/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/wiko/s9091/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/wiko/s9091/proprietary/bin/shutdown:system/bin/shutdown \
    vendor/wiko/s9091/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
    vendor/wiko/s9091/proprietary/bin/memorydumper:system/bin/memorydumper \
    vendor/wiko/s9091/proprietary/bin/mobile_log_d:system/bin/mobile_log_d \
    vendor/wiko/s9091/proprietary/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/wiko/s9091/proprietary/framework/com.mediatek.location.provider.jar:system/framework/com.mediatek.location.provider.jar
